### ISSUE TITLE
Question about services with REST

### ISSUE THREAD

**Issue by sydekumf** [angularjs-de/dpunkt-buch-beispiele#5]
Hi, I am currently at chapter 4.3 where you have to refactor the `BookDataService` in order to communicate with a REST backend. I have a question regarding the architecture: You refactored the service in a way so that you had to refactor all components which use this service in order to function properly. Also all components using the service have to "know" about the inner implementation of the service (which is REST) because they have to switch to promises.
In the beginning of your book you talked about the advantage that you can easily change services and their implementation without refactoring calling components. So my question is: Why didn't you implement the promise inside the `BookDataService` just returning the book object?

Thanks a lot, the book rocks :+1:

**Comment by justphil** [comment]
Hi @sydekumf,

Thank you very much for your feedback. :-)
Of course, you're completely right. It is a much better idea to return promises in the `BookDataService` in all chapters before the introduction of `$http`. This would indeed allow us to change the implementation of the `BookDataService` without any changes in the using components (`BookListCtrl`, etc.).

In fact this is also the way that we proclaim in our workshops. But the book examples are meanwhile 2 years old. At the beginning of thinking about the book's content we just didn't think about this benefit. :-)
And we're not able to change it here in the repo because it wouldn't be consistent with the printed book. Meehhh... :-D

Just a clue for all others readers that don't know what we're talking about. In the chapters before the introduction of `$http` we could have made all our API functions in the `BookDataService` async and returning promises to really stick to the API that is introduced after the `$http` change. Let's consider the API function `getBooks()` to see what needs to be done in order to accomplish that.

Current impl. before introducing `$http`:

```
srv.getBooks = function() {
    // Copy the array in order not to expose the internal data structure
    return angular.copy(srv._books);
};
```

Better impl. before introducing `$http`:

```
srv.getBooks = function() {
    // Copy the array in order not to expose the internal data structure
    return $q.when({ data: angular.copy(srv._books) });
};
```

Of course you need to inject the `$q` service that is needed in order to use the `when()`function. What `when()` does in the scenario is actually creating a promise (which is returned) and asynchronously resolving it with the passed data.

The using components need to be changed accordingly. Similar to the state after the `$http` refactoring (e.g. see https://github.com/angularjs-de/dpunkt-buch-beispiele/blob/master/ch04_03_http/app/scripts/controllers/book_list.js).

Hope that I could help.

Bye,
Phil
